### PR TITLE
Update version of terraform-google-scheduled-function module + Add ab…

### PR DESCRIPTION
**Pull request by ocervell**
Ability to share topic and scheduler across SLOs + Fix for scheduler bug

### CODE REVIEW

**Review by morgante — APPROVED** [review]

**Comment by Djabx** [comment]
Ok I think it's great but it miss the creation of the scheduler / pubsub associated.

Like I said in #23 I would probably prefere something like `slo-pipeline`; a module to great the upper part of the pipeline.

**Comment by Djabx** [comment]
BTW I rebase this branch to the master here: https://github.com/Djabx/terraform-google-slo/tree/fix-scheduler-module-bug
Should I make other modification ? A new PR ?
What do you prefer ?

**Comment by ocervell** [comment]
Please make a new PR and I'll close this one. Thanks !

**Comment by Djabx** [comment]
> Please make a new PR and I'll close this one. Thanks !

It's now in PR #23

**Pull request closed without merging**
